LIBNAME = myframe
SUBFFIX	= .a
BINDIR	= bin
LIBDIR	= lib
OBJDIR	= obj
TMPDIR  = $(BINDIR) $(LIBDIR) $(OBJDIR)

CXX     = g++
AR      = ar
CCFLAG	= -g -Wall -D_DEBUG_
SOFLAG  = -rcs
INCFLAG	= -I./

TEST	= $(foreach d,$(shell ls test|grep -v mysql),test/$(d))
DIRS	= memory socket thread httpd utils $(TEST)
SRCS	= $(foreach d,$(DIRS),$(wildcard $(d)/*.cpp))
OBJS	= $(patsubst %.cpp,$(OBJDIR)/%.o,$(SRCS))
SOOBJS	= $(filter-out $(OBJDIR)/test/%.o,$(OBJS))
APPOBJS	= $(filter $(OBJDIR)/test/%.o,$(OBJS))

#NULLSTR =
#SPACE	= $(NULLSTR) #end of the line
#VPATH	= $(subst $(SPACE),:,$(DIRS))

TARGET	= $(LIBDIR)/lib$(LIBNAME)$(SUBFFIX)
APPLIBS = $(TARGET) -lpthread

all : dir lib app
lib : $(TARGET)

dir:
	@-rm -rf $(TMPDIR)
	@-mkdir $(TMPDIR)
	@-mkdir -p $(foreach d, $(DIRS), $(OBJDIR)/$(d))

$(TARGET) : $(SOOBJS)
	$(AR) $(SOFLAG) $@ $^ $(SOLIBS)

app: $(APPOBJS)
	$(foreach a,$(APPOBJS),$(CXX) -pg -o $(BINDIR)/$(basename $(notdir $(a))) $(a) $(APPLIBS);)

$(OBJDIR)/%.o : %.cpp
	$(CXX) $(CCFLAG) $(INCFLAG) -c $< -o $@
$(OBJDIR)/%.o : %.c
	$(CXX) $(CCFLAG) $(INCFLAG) -c $< -o $@

.PHONY : clean
clean :
	-rm -rf $(TMPDIR)
